# Generated by Django 4.2.9 on 2026-02-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(help_text='Vehicle license plate number (e.g., ABC-1234)', max_length=20)),
                ('inspection_date', models.DateField(help_text='Date of the inspection (cannot be in the past)')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('passed', 'Passed'), ('failed', 'Failed')], default='scheduled', help_text='Current status of the inspection', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the inspection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the inspection was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the inspection was last updated')),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'ordering': ['-inspection_date', '-created_at'],
                'indexes': [models.Index(fields=['vehicle_plate'], name='inspections_vehicle_274f17_idx'), models.Index(fields=['inspection_date'], name='inspections_inspect_3cc2a0_idx'), models.Index(fields=['status'], name='inspections_status_094ca4_idx')],
            },
        ),
    ]
