# Generated by Django 4.2.9 on 2026-02-05 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('passed', 'Passed'), ('failed', 'Failed')], help_text='Previous status before the change', max_length=20)),
                ('new_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('passed', 'Passed'), ('failed', 'Failed')], help_text='New status after the change', max_length=20)),
                ('changed_at', models.DateTimeField(help_text='When the status change occurred')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the change', null=True)),
                ('inspection', models.ForeignKey(help_text='The inspection this history record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inspections.inspection')),
            ],
            options={
                'verbose_name': 'Inspection History',
                'verbose_name_plural': 'Inspection Histories',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['inspection', '-changed_at'], name='inspections_inspect_e5ded6_idx')],
            },
        ),
    ]
